"""Add products tables

Revision ID: 8e322e7bb4a3
Revises: 4e0805c6a907
Create Date: 2024-10-13 13:54:23.119706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e322e7bb4a3'
down_revision: Union[str, None] = '4e0805c6a907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
